SELECT C_CUSTOMER_SK AS CUSTOMER_ID,
       C_FIRST_NAME AS FIRST_NAME,
       C_LAST_NAME AS LAST_NAME,
       C_CURRENT_CDEMO_SK AS CDEMO_SK,
       C_CURRENT_HDEMO_SK AS HDEMO_SK
FROM {{ source('tpcds', 'CUSTOMER') }}
WHERE C_CUSTOMER_SK IS NOT NULL