WITH WEB_SALES AS (
SELECT 
    WS_BILL_CUSTOMER_SK AS CUSTOMER_ID,
    WS_SOLD_DATE_SK AS SOLD_DATE_SK,
    WS_ORDER_NUMBER AS ORDER_NUMBER,
    WS_ITEM_SK AS ITEM_SK,
    WS_NET_PAID AS NET_PAID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SALES
WHERE
    WS_BILL_CUSTOMER_SK IS NOT NULL
),
DATE AS (
SELECT
    D_DATE_SK,
    D_DATE
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM
)
SELECT
    W.CUSTOMER_ID,
    D.D_DATE AS SOLD_DATE,
    W.ORDER_NUMBER AS TICKET_OR_ORDER,
    W.ITEM_SK,
    W.NET_PAID,
    'WEB' AS CHANNEL
FROM WEB_SALES W
INNER JOIN DATE D ON W.SOLD_DATE_SK = D.D_DATE_SK