WITH CUSTOMER_SALES AS (
    SELECT
        CUSTOMER_ID,
        CHANNEL,
        MAX(SOLD_DATE) AS LAST_PURCHASE_DATE,
        COUNT(*) AS FREQUENCY,
        SUM(NET_PAID) AS MONETARY
    FROM {{ ref('stg_all_sales') }}
    GROUP BY CUSTOMER_ID, CHANNEL
)

SELECT 
    CUSTOMER_ID,
    CHANNEL,
    DATEDIFF('day', LAST_PURCHASE_DATE, current_date) AS RECENCY_DAYS,
    FREQUENCY,
    MONETARY
FROM CUSTOMER_SALES