WITH BASE AS (
    SELECT * FROM {{ ref('int_customer_rfm_base') }}
)
SELECT
    CUSTOMER_ID,
    CHANNEL,
    RECENCY_DAYS,
    FREQUENCY,
    MONETARY,
    NTILE(5) OVER (PARTITION BY CHANNEL ORDER BY RECENCY_DAYS ASC) AS R_SCORE,
    NTILE(5) OVER (PARTITION BY CHANNEL ORDER BY FREQUENCY DESC) AS F_SCORE,
    NTILE(5) OVER (PARTITION BY CHANNEL ORDER BY MONETARY DESC) AS M_SCORE
FROM BASE